# Generated by Django 4.2.6 on 2023-12-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_oil_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='oil',
            name='imagename',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='oil',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
