# Generated by Django 4.2.6 on 2023-12-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_oil_imagename_alter_oil_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oil',
            name='imagename',
        ),
        migrations.AlterField(
            model_name='oil',
            name='image',
            field=models.ImageField(upload_to='app/static/saved'),
        ),
    ]
